version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/PublicLibrarySystem-UI"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(npm)"
    groups:
      ui-dependencies:
        patterns:
          - "*"
    reviewers:
      - "ninepiece2"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(github-actions)"
    groups:
      github-actions:
        patterns:
          - "*"
    reviewers:
      - "ninepiece2"
  
  - package-ecosystem: "nuget"
    directory: "/PublicLibrarySystem-API"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "America/Toronto"
    commit-message:
      prefix: "deps(nuget)"
    groups:
      api-dependencies:
        patterns:
          - "*"
    reviewers:
      - "ninepiece2"
