INSERT INTO [dbo].[Books]
           ([Title]
           ,[Author]
           ,[ISBN]
           ,[Genre]
           ,[Publisher]
           ,[Pages]
           ,[Language]
           ,[Description]
           ,[IsAvailable]
           ,[PublishedDate])
VALUES
  (
    'The Let Them Theory: A Life-Changing Tool That Millions of People Can''t Stop Talking About',
    'Mel Robbins',
    '1401971369',
    'Self-help / Motivational',
    'Hay House LLC',
    336,
    'English',
    '',
    1,
    '2024-12-24'
  ),
  (
    'Sunrise on the Reaping (A Hunger Games Novel) (The Hunger Games)',
    'Suzanne Collins',
    NULL,
    'Dystopian Fiction',
    'Scholastic Press',
    NULL,
    'English',
    '',
    1,
    '2025-03-18'
  ),
  (
    'How to Catch the Easter Bunny',
    'Adam Wallace',
    NULL,
    'Children''s Literature',
    'Sourcebooks Wonderland',
    NULL,
    'English',
    '',
    1,
    '2017-02-01'
  ),
  (
    'Forgotten Home Apothecary : 250 Powerful Remedies at Your Fingertips',
    'Dr. Nicole Apelian',
    NULL,
    'Health / Herbal',
    'Global Brother',
    NULL,
    'English',
    'Standard Edition (October 8, 2024)',
    1,
    '2024-10-08'
  ),
  (
    'The Alchemist, 25th Anniversary: A Fable About Following Your Dream',
    'Paulo Coelho',
    NULL,
    'Philosophical Fiction / Inspirational',
    'HarperOne',
    NULL,
    'English',
    'Anniversary edition (April 15, 2014)',
    1,
    '2014-04-15'
  ),
  (
    'It''s Not Easy Being a Bunny: An Early Reader Book for Kids (Beginner Books)',
    'Marilyn Sadler',
    NULL,
    'Children''s Literature',
    'Random House Books for Young Readers',
    NULL,
    'English',
    'Unknown edition (September 12, 1983)',
    1,
    '1983-09-12'
  ),
  (
    'Say You''ll Remember Me',
    'Abby Jimenez',
    NULL,
    'Contemporary Fiction / Romance',
    'Forever',
    NULL,
    'English',
    '',
    1,
    NULL
  ),
  (
    'Fight: Inside the Wildest Battle for the White House',
    'Jonathan Allen',
    NULL,
    'Political Non-Fiction',
    'William Morrow',
    NULL,
    'English',
    '',
    1,
    '2025-04-01'
  ),
  (
    'The New Menopause: Navigating Your Path Through Hormonal Change with Purpose, Power, and Facts',
    'Mary Claire Haver MD',
    NULL,
    'Health / Self-help',
    'Rodale Books',
    NULL,
    'English',
    '',
    1,
    '2024-04-30'
  ),
  (
    'There Are Moms Way Worse Than You: Irrefutable Proof That You Are Indeed a Fantastic Parent',
    'Glenn Boozan',
    NULL,
    'Humor / Parenting',
    'Workman Publishing Company',
    NULL,
    'English',
    '',
    1,
    '2022-03-29'
  ),
  (
    'Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones',
    'James Clear',
    '0735211299',
    'Self-help / Personal Development',
    'HarperOne',
    NULL,
    'English',
    '',
    1,
    '2018-10-16'
  ),
  (
    'The Book of Awakening: Having the Life You Want by Being Present to the Life You Have (20th Anniversary Edition)',
    'Mark Nepo',
    '1590035003',
    'Inspirational / Spiritual',
    'Hay House',
    NULL,
    'English',
    '',
    1,
    '2017-11-14'
  ),
  (
    'Cozy Friends: Coloring Book for Adults and Teens Featuring Super Cute Animal Characters with Easy and Simple Designs for Relaxation',
    'Coco Wyo',
    'B0D4YLQRMP',
    'Coloring / Art Therapy',
    'Scholastic Inc.',
    NULL,
    'English',
    '',
    1,
    '2023-05-20'
  ),
  (
    'Who Believed in You: How Purposeful Mentorship Changes the World',
    'David McCormick',
    '140023591X',
    'Business / Leadership',
    'Thomas Nelson',
    NULL,
    'English',
    '',
    1,
    '2021-09-15'
  ),
  (
    'Fearless (The Powerless Trilogy)',
    'Lauren Roberts',
    '1665955465',
    'Fiction / Thriller',
    'Random House',
    NULL,
    'English',
    '',
    1,
    '2022-06-01'
  ),
  (
    'Umma: A Korean Mom''s Kitchen Wisdom and 100 Family Recipes',
    'Sarah Ahn',
    '1954210566',
    'Cookbook / Family Recipes',
    'Penguin',
    NULL,
    'English',
    '',
    1,
    '2020-08-05'
  ),
  (
    'Next Conversation: Argue Less, Talk More',
    'Jefferson Fisher',
    '0593718720',
    'Self-help / Communication',
    'HarperCollins',
    NULL,
    'English',
    '',
    1,
    '2019-03-12'
  ),
  (
    'The Frozen River: A GMA Book Club Pick: A Novel',
    'Ariel Lawhon',
    '059379625X',
    'Literary Fiction',
    'HarperOne',
    NULL,
    'English',
    '',
    1,
    '2020-01-01'
  ),
  (
    'Pete the Cat and the Easter Basket Bandit: Includes Poster, Stickers, and Easter Cards!: An Easter And Springtime Book For Kids',
    'James Dean',
    '0062868373',
    'Children''s Literature / Activity Book',
    'Scholastic',
    NULL,
    'English',
    '',
    1,
    '2023-01-01'
  ),
  (
    'Dissolving Illusions: Disease, Vaccines, and the Forgotten History 10th Anniversary Edition',
    'Roman Bystrianyk',
    'B0CZ61XLXH',
    'Health / Alternative Medicine',
    'HarperCollins',
    NULL,
    'English',
    '',
    1,
    '2021-06-01'
  ),
  (
    'Somebunny Loves You: A Sweet and Silly Easter Board Book for Babies and Toddlers (Punderland)',
    'Rose Rossner',
    '1728223431',
    'Children''s Board Book',
    'Scholastic',
    NULL,
    'English',
    '',
    1,
    '2022-02-01'
  ),
  (
    'Onyx Storm (Deluxe Limited Edition) (The Empyrean, 3)',
    'Rebecca Yarros',
    '1649374186',
    'Fantasy / Science Fiction',
    'Amazon Books',
    NULL,
    'English',
    '',
    1,
    '2022-12-01'
  ),
  (
    'Journey to Self: Unlocking Your Inner Potential',
    'Alex Morgan',
    '9781234567897',
    'Self-help / Personal Development',
    'Penguin Random House',
    250,
    'English',
    'A guide to unlocking your inner strength and achieving personal success.',
    1,
    '2020-05-15'
  ),
  (
    'Mysteries of the Universe',
    'Dr. Jane Goodall',
    '9789876543210',
    'Science / Non-Fiction',
    'Oxford University Press',
    320,
    'English',
    'An exploration into the cosmos and the secrets it holds.',
    1,
    '2019-11-10'
  ),
  (
    'Love in the Time of Algorithms',
    'Emily Bronte',
    '9781122334455',
    'Romance / Contemporary',
    'HarperCollins',
    280,
    'English',
    'A modern romance in the digital age.',
    1,
    '2021-02-14'
  ),
  (
    'The Art of Mindfulness',
    'Thich Nhat Hanh',
    '9786677889900',
    'Spirituality / Self-help',
    'Parallax Press',
    150,
    'English',
    'Techniques and practices for living in the moment.',
    1,
    '2018-08-20'
  ),
  (
    'Financial Freedom: A Roadmap to Wealth',
    'Robert Kiyosaki',
    '9783344556677',
    'Business / Finance',
    'Warner Books',
    400,
    'English',
    'Strategies to build wealth and achieve financial independence.',
    1,
    '2017-03-05'
  ),
  (
    'The Quiet Mind: Finding Peace in a Chaotic World',
    'Susan Cain',
    '9789988776655',
    'Psychology / Self-help',
    'Viking',
    360,
    'English',
    'A look at introversion and how to harness its power.',
    1,
    '2016-09-30'
  ),
  (
    'Adventures in Cooking: Global Recipes for the Home Chef',
    'Gordon Ramsay',
    '9785544332211',
    'Cookbook / Culinary',
    'Penguin Random House',
    500,
    'English',
    'Delicious recipes and cooking techniques from around the world.',
    1,
    '2020-07-22'
  ),
  (
    'The Digital Nomad Lifestyle',
    'Tim Ferriss',
    '9784433221100',
    'Business / Lifestyle',
    'Portfolio',
    310,
    'English',
    'How to work remotely and travel the world.',
    1,
    '2019-04-10'
  );

INSERT INTO [dbo].[Books]
           ([Title]
           ,[Author]
           ,[ISBN]
           ,[Genre]
           ,[Publisher]
           ,[Pages]
           ,[Language]
           ,[Description]
           ,[IsAvailable]
           ,[PublishedDate])
VALUES
  (
    'The Housemaid''s Secret',
    'Freida McFadden',
    '0349132615',
    'Mystery',
    'Bookouture',
    NULL,
    'English',
    '',
    1,
    '2023-07-11'
  ),
  (
    'Don''t Push the Button! An Easter Surprise: (Easter Board Book, Interactive Books For Toddlers, Childrens Easter Books Ages 1-3)',
    'Bill Cotter',
    '1492680117',
    'Children''s',
    'Sourcebooks Jabberwocky',
    NULL,
    'English',
    '',
    1,
    '2019-02-05'
  ),
  (
    'Chicka Chicka Boom Boom (Board Book)',
    'Bill Martin Jr.',
    '9781442450707',
    'Children''s',
    'Little Simon',
    NULL,
    'English',
    '',
    1,
    '2012-01-01'
  ),
  (
    'The Rainbow Fish',
    'Marcus Pfister',
    '1558585362',
    'Fiction',
    'NorthSouth Books',
    NULL,
    'English',
    '',
    1,
    '1999-01-27'
  ),
  (
    'On Tyranny: Twenty Lessons from the Twentieth Century',
    'Timothy Snyder',
    '0804190119',
    'Non-fiction',
    'Crown; First Edition',
    NULL,
    'English',
    '',
    1,
    '2017-02-28'
  ),
  (
    'Shred Happens: So Easy, So Good: 100+ Protein-Packed Mediterranean Favorites with a Low-Carb Twist; A Cookbook',
    'Arash Hashemi',
    '0593796535',
    'Health',
    'Rodale Books',
    256,
    'English',
    '',
    1,
    '2025-03-18'
  ),
  (
    'Verity',
    'Colleen Hoover',
    '1538724731',
    'Fiction',
    'Grand Central Publishing; Reprint edition',
    NULL,
    'English',
    '',
    1,
    '2021-10-26'
  ),
  (
    'Brown Bear, Brown Bear, What Do You See?',
    'Bill Martin Jr.',
    '0805047905',
    'Children''s',
    'Henry Holt Books for Young Readers; BRDBK edition',
    NULL,
    'English',
    '',
    1,
    '1996-09-15'
  ),
  (
    'I Just Wish I Had a Bigger Kitchen: And Other Lies I Think Will Make Me Happy',
    'Kate Strickler',
    '0764243780',
    'Lifestyle',
    'Bethany House Publishers',
    192,
    'English',
    '',
    1,
    '2025-08-26'
  ),
  (
    'The Action Bible: God''s Redemptive Story',
    'Sergio Cariello (Illustrator)',
    '083077744X',
    'Religious',
    'David C Cook; Revised edition',
    832,
    'English',
    '',
    1,
    '2020-09-01'
  ),
  (
    'Rose Book of Bible Charts, Maps, and Time Lines',
    'Rose Publishing',
    '1596360224',
    'Religious',
    'Rose Publishing; Special Edition',
    NULL,
    'English',
    '',
    1,
    '2015-03-13'
  ),
  (
    'The God of the Woods: A Novel',
    'Liz Moore',
    '0593418913',
    'Fiction',
    'Riverhead Books',
    496,
    'English',
    '',
    1,
    '2024-07-02'
  ),
  (
    'Purposeful Performance: The Secret Mix of Connecting, Leading, and Succeeding',
    'Jonathan Stanley',
    NULL,
    'Mystery',
    'EarthyPilot Publishing',
    NULL,
    'English',
    '',
    1,
    '2024-08-21'
  ),
  (
    'How to Catch a Dinosaur',
    'Adam Wallace',
    '1492680524',
    'Fiction',
    'Sourcebooks Wonderland',
    40,
    'English',
    '',
    1,
    '2019-09-03'
  ),
  (
    'The Psychology of Money: Timeless lessons on wealth, greed, and happiness',
    'Morgan Housel',
    '0857197681',
    'Fiction',
    'Harriman House',
    NULL,
    'English',
    '',
    1,
    '2020-09-08'
  ),
  (
    'So Easy So Good: Delicious Recipes and Expert Tips for Balanced Eating (A Cookbook)',
    'Kylie Sakaida',
    '166803798X',
    'Fiction',
    'S&S/Simon Element',
    272,
    'English',
    '',
    1,
    '2025-04-08'
  ),
  (
    'Fahrenheit 451',
    'Ray Bradbury',
    '9781451673319',
    'Fiction',
    'Simon & Schuster; Reissue edition',
    NULL,
    'English',
    '',
    1,
    '2012-01-10'
  ),
  (
    'Don''t Believe Everything You Think (Expanded Edition): Why Your Thinking Is The Beginning & End Of Suffering (Graduation Gift) (Books By Joseph Nguyen)',
    'Joseph Nguyen',
    NULL,
    'Fiction',
    'Authors Equity',
    192,
    'English',
    '',
    1,
    '2024-10-29'
  ),
  (
    'Oh, the Places You''ll Go!',
    'Dr. Seuss',
    '0679805273',
    'Fiction',
    'Random House Books for Young Readers',
    56,
    'English',
    '',
    1,
    '1990-01-22'
  ),
  (
    'Never Touch a Grumpy Bunny!',
    'Rosie Greening',
    '1800582684',
    'Fiction',
    'Make Believe Ideas',
    NULL,
    'English',
    '',
    1,
    '2021-02-01'
  ),
  (
    'World of Eric Carle, Around the Farm 30-Button Animal Sound Book - Great for First Words - PI Kids',
    'PI Kids',
    '1450805752',
    'Fiction',
    'PI Kids',
    24,
    'English',
    '',
    1,
    '2013-02-01'
  ),
  (
    'James: A Novel',
    'Percival Everett',
    '0385550367',
    'Fiction',
    'Doubleday; First Edition',
    320,
    'English',
    '',
    1,
    '2024-03-19'
  ),
  (
    'The Housemaid Is Watching',
    'Freida McFadden',
    '1464221138',
    'Fiction',
    'Poisoned Pen Press',
    NULL,
    'English',
    '',
    1,
    '2024-06-11'
  ),
  (
    'A Court of Thorns and Roses Paperback Box Set (5 books) (A Court of Thorns and Roses, 9)',
    'Sarah J. Maas',
    '1639730192',
    'Fiction',
    'Bloomsbury Publishing',
    NULL,
    'English',
    '',
    1,
    '2022-11-01'
  ),
  (
    'Code Name: Pale Horse: How I Went Undercover to Expose America''s Nazis',
    'Scott Payne',
    '1668032902',
    'Fiction',
    'Atria Books',
    256,
    'English',
    '',
    1,
    '2025-03-25'
  ),
  (
    'My First Library: Boxset of 10 Board Books for Kids',
    'Wonder House Books',
    '9789387779266',
    'Children''s',
    'Wonder House Books; First Edition',
    NULL,
    'English',
    '',
    1,
    '2018-04-25'
  ),
  (
    'The Four Agreements: A Practical Guide to Personal Freedom (A Toltec Wisdom Book)',
    'Don Miguel Ruiz',
    '9781878424310',
    'Fiction',
    'Amber-Allen Publishing',
    NULL,
    'English',
    '',
    1,
    '1997-11-07'
  ),
  (
    'Try Not to Laugh Challenge, Easter Joke Book for Kids: Easter Basket Stuffer for Boys, Girls, Teens & Adults, Fun Easter Activity Book with Cute ... Easter Activities for the Whole Family!',
    'Easter Bunny Press',
    '1986554902',
    'Fiction',
    'CreateSpace Independent Publishing Platform',
    NULL,
    'English',
    '',
    1,
    '2018-03-17'
  ),
  (
    'The Hardest Hidden Pictures Book Ever: The Hardest Hidden Pictures Book Ever (Highlights Hidden Pictures Puzzles) Over 1,500 Hidden Objects to Search and Find, Hardest Look-and-Find Book',
    'Highlights (Creator)',
    '1644723344',
    'Fiction',
    'Highlights Press',
    NULL,
    'English',
    '',
    1,
    '2021-03-09'
  ),
  (
    'Little Blue Bunny: A Heartwarming Easter Basket Stuffer for Children (Little Heroes, Big Hearts)',
    'Erin Guendelsberger',
    '1728254485',
    'Fiction',
    'Sourcebooks Wonderland',
    40,
    'English',
    '',
    1,
    '2022-02-01'
  );
